FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app

CMD ["streamlit", "run", "ui/streamlit_main.py", "--server.port=8501", "--server.address=0.0.0.0"]
