"""Recreate migrations

Revision ID: 0144b220c513
Revises: 
Create Date: 2025-03-27 15:44:22.659912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0144b220c513'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_messages', 'users', ['user_id'], ['id'])
    op.alter_column('chat_messages', 'user_id', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'user_id')
    # ### end Alembic commands ###
